author: "Prof. Ashraf Fawzy Nabhan"
subject: "Evidence-Based Healthcare"
keywords: "EBM"
format: 
  beamer:
    number-sections: false
    aspectratio: 169
    navigation: horizontal
    theme: CambridgeUS
    slide-level: 2
    fontsize: 14pt
    section-titles: true
    incremental: false
editor: visual
