---
title: "Finding the Evidence"
subtitle: "Standards for Evidence Synthesis"
---

## Bibliographic databases

| Database | Provider  | Platform         |
|:---------|:----------|:-----------------|
| MEDLINE  | NLM       | PubMed           |
| CENTRAL  | Wiley     | Cochrane Library |
| MEDLINE  | Clarivate | Web of Science   |
| Embase   | Elsevier  | embase.com       |

: {tbl-colwidths="\[30,30,60\]"}

## DB, explained

-   consists of a 2D table

    -   rows = records

    -   columns = fields (each field = a specific type of data)

-   Fields may contain either free or controlled data

| Field      | tag    |
|:-----------|:-------|
| Title      | \[ti\] |
| Abstract   | \[ab\] |
| MeSH terms | \[mh\] |

: {tbl-colwidths="\[50,50\]"}

## Concepts and terms

-   Concepts

    -   Population

    -   Intervention

    -   Study design

-   Terms are synonyms for each concept

    -   use your knowledge or browse the mesh database

## Structure

-   Line by line format

    -   Each line = one term in one specific field

    -   Must search in both free and controlled fields

-   Boolean operators

    -   use OR to combine synonyms

    -   use AND to combine concepts

## Search filters for RCTs in MEDLINE \[PubMed\] {.smaller}

1.  randomized controlled trial \[pt\]
2.  controlled clinical trial \[pt\]
3.  clinical trials as topic \[mesh:noexp\]
4.  randomized \[tiab\]
5.  placebo \[tiab\]
6.  randomly \[tiab\]
7.  trial \[ti\]
8.  #1 OR #2 OR #3 OR #4 OR #5 OR #6 OR #7
9.  animals \[mh\] NOT humans \[mh\]
10. #8 NOT #9

## Peer review

-   DB name, stating the platform for each

-   Full search strategy for each DB, copy-paste exactly as run

-   Limits and restrictions (e.g., language, study design)

-   Boolean and proximity operators

-   Subject headings

-   Text word searching

-   Synonyms, related terms, variant spellings, truncation and wildcards

## Endgame

For adults with low back pain, does paracetamol compared with placebo, improve quality of life?

-   Conceptual knowledge: Identify the concepts.

-   Procedural knowledge: develop a comprehensive search strategy
